### ISSUE TITLE
Ability to edit Title, Author, and Subject in document records.

### ISSUE THREAD

**Issue by JBSmo** [rffrasca/PDFKeeper#16]
**Is your feature request related to a problem? Please describe.**
On initial evaluation of the software I made a couple of errors on the file record entry, that I really didn't notice until the table was populated with more entries. I couldn't find a way to correct any of those erroneous fields. Title, Author, and Subject were the ones I tried. I didn't try Category, since I made no mistakes in that field, and I don't use Tax Year at all in my intended application.

**Describe the solution you'd like**
I tried editing the Category field for one of the file records, and using the help file, I was able to do that. I also tried bulk editing by selecting multiple records. I like this process. Perhaps a similar process for editing Title, Author or Subject?

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by rffrasca** [comment]
This enhancement will consist of three features: Set Title, Set Author, and Set Subject. These new features will be similar to the existing Set Category and Set Tax Year features for consistency.

**Comment by rffrasca** [comment]
PDFKeeper 9.1.0 was released today.
