### ISSUE TITLE
Progress Bar While Uploading Pdf

### ISSUE THREAD

**Issue by Sohail2949000** [rffrasca/PDFKeeper#40]
Hello Sir,

First of all, then you for an amazing software, Loved it.

 
Can we have a progress bar when we are uploading file so when we upload a document, we can see the progress bar.
Because I uploaded pdf and go to another program to work after a minute when I come back it was still uploading and I thought it hangs and I restart the application and had to upload the file again, so if we have a progress bar, we can see it is uploading, and we can wait.

and is this will be possible in future to use it with MySQL because we are already working with MySQL if it supports with that it would be really helpful and supporting for us.

Thanks again,
Regards.

**Comment by rffrasca** [comment]
Hello Sohail,
Thank you for the kind words.

I can add a marquee style progress bar that would appear on the status bar during the upload. This progress bar would replace the "green clock" that currently appears during the upload. As for MySQL support, please submit a feature request and I can add it in the next major release.

**Comment by Sohail2949000** [comment]
Dear Sir

Thank You for your support.

Sure, I will submit a feature request.

Regards,
Sohail
