### ISSUE TITLE
Return fulltext search result token context or location

### ISSUE THREAD

**Issue by Exynom** [rffrasca/PDFKeeper#7]
Ideally, when using the fulltext search a user could be returned where the phrase was found in the document, or the surrounding few words of where it was found. Getting the result should be pretty straighforward by modifying the fts5 query a little, and it could either be displayed in a new column in the filtered documents browser or in an extra tab of the bottom left details panel (the one with "Notes", "Keywords" etc). 

Thanks a ton for this awesome project btw, it has become a very important tool for managing my academic pdf library!

Cheers!

**Comment by Exynom** [comment]
Hello Robert, 

thanks for the lightning fast answer!

Yes exactly, or probably rather the `snippet()` function, so as to not have the full pdf transcript returned, but only the snippet containing the search terms. If I understand it correctly the `highlight()` function will return the full contents of the specified column.

Cheers,
Andreas

**Comment by rffrasca** [comment]
Hello Andreas,

After performing some test queries with the snippet() function, I reached a conclusion that it would be best to show the results in a separate details tab (bottom left of the form) for the selected document. This tab would only be enabled when a search by text is performed.

I can add this enhancement to the Todo list for version 8.0.0 that is in development.

Thanks,
Robert

**Comment by rffrasca** [comment]
PDFKeeper 8.0.0 was released today.
